### ISSUE TITLE
LoadingPage Animation

### ISSUE THREAD

**Issue by zhinea** [euxzy/portfolio#3]
bagaimana cara mengubah svg LoadingPage nya? 

dan dimana cara mendapatkan svg nya?

**Comment by euxzy** [comment]
untuk svg nya bisa buat sendiri menggunakan figma, photoshop, illustrator, gimp, dll

kalau mau buat svg pake figma, bisa ikuti tutorial ini https://www.youtube.com/watch?v=vJNVramny9k
